### PR TITLE
shopfloor: fix zone_picking._scan_source_location

### PR DESCRIPTION
**Pull request by simahawk**
Lines from source location should respect the same domain
as the one used to retrieve all available lines (eg: not done lines).

ref: 1811

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Review by jbaudoux — APPROVED** [review]
LGTM

**Comment by simahawk** [comment]
WTH is going on w/ the bot? :thinking: 
@sbidoul do you know if there's any issue w/ the bot or it's just travis taking too much time?

**Comment by simahawk** [comment]
Let's give it another try...

/ocabot merge patch

**Comment by sbidoul** [comment]
Nah the bot is just fine. Travis has not reported to GitHub: look at the yellow dot, there is only runbot.

**Comment by simahawk** [comment]
Seems we finished Travis' credits.. I bump and merge manually.

**Pull request merged**
