### PR TITLE
[13.0->14.0][oca-port-pr-#125] shopfloor: refine model and views

### PR DESCRIPTION
**Pull request by sebalix**
Port of #125 from 13.0 to 14.0.

### CODE REVIEW

**Comment by sebalix** [comment]
Same story than https://github.com/OCA/wms/pull/252

**Comment by simahawk** [comment]
misisng anything then?

**Comment by sebalix** [comment]
On this module from this specific PR, we miss only this small change.
Other changes have been done (like the profile management which has been moved to `shopfloor_base`) but it is part of other PRs.

**Pull request merged**
