### PR TITLE
[14.0][MIG] stock_picking_consolidation_priority

### PR DESCRIPTION
**Pull request by hparfr**
From stock-logistics-warehouse

### CODE REVIEW

**Comment by hparfr** [comment]
@guewen please have a look to https://github.com/OCA/wms/commit/7a6f119991b78d72af0464c444305404d69ae834

**Comment by rousseldenis** [comment]
@hparfr Why moving here as IMHO it makes sense to let it in stock related repo? It does not have complex dependencies (stock).

**Comment by guewen** [comment]
> Why moving here as IMHO it makes sense to let it in stock related repo? It does not have complex dependencies (stock).

This is a request from @jgrandguillaume

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@hparfr please squash last commit

**Pull request merged**
