### PR TITLE
[13.0] shopfloor - single pack transfer: when pack is empty, raise same error as in zone picking

### PR DESCRIPTION
**Pull request by jbaudoux**
Raise an error "Package has no product to take" when scanning an empty pack

@sebalix I had not seen you recently already fixed the internal error. What you think about raising this message instead of package not allowed ?

### CODE REVIEW

**Review by sebalix — COMMENTED** [review]
LG, a unit test is welcome however :)

**Comment by jbaudoux** [comment]
> LG, a unit test is welcome however :)

@sebalix Test added

**Comment by simahawk** [comment]
@jbaudoux now is red :rofl:

**Comment by sebalix** [comment]
Note (to myself?): would need to port this to 14.0 as well

**Comment by simahawk** [comment]
@jbaudoux @sebalix shall we move fwd here?

**Comment by jbaudoux** [comment]
> @jbaudoux @sebalix shall we move fwd here?

Thanks for the ping, I'll fix the PR

**Comment by jbaudoux** [comment]
@simahawk @sebalix PR is green. The test has been fixed

**Comment by simahawk** [comment]
@jbaudoux cool, can you rewrite your commit msg pls? Eg:
```
shopfloor: single_pack_transfer fix error msg

When pack is empty, use the same message of the zone picking.
```

**Comment by jbaudoux** [comment]
> @jbaudoux cool, can you rewrite your commit msg pls? Eg:
> 
> ```
> shopfloor: single_pack_transfer fix error msg
> 
> When pack is empty, use the same message of the zone picking.
> ```

done

**Review by simahawk — APPROVED** [review]
@sebalix  ping

**Review by sebalix — APPROVED** [review]

**Pull request merged**
