### PR TITLE
[13.0] Add shopfloor barcode app

### PR DESCRIPTION
**Pull request by simahawk**
Specs are still here: https://docs.google.com/presentation/d/1A5TVJXryqod7IwVIl03mDUJIUGzqJ-T2FzSWA90zAvw/edit#slide=id.p

### CODE REVIEW

**Comment by simahawk** [comment]
I've canceled the build as it's useless to run it now.

**Comment by ritco** [comment]
@simahawk is there still a plan to create a scan app?

**Comment by simahawk** [comment]
@ritco the app is here, in this PR actually. The behavior is the on described in the specs linked above.
For now we are in heavy testing / fixing phase. It will be deployed on production very soon.

**Comment by simahawk** [comment]
@guewen would you have time to check why travis build is failing?

**Comment by hparfr** [comment]
FYI I plan to work on the reception soon.

**Review by guewen — APPROVED** [review]
:tada:

**Review by TDu — APPROVED** [review]

**Review by jgrandguillaume — APPROVED** [review]
Functional review: All good. Thanks you for this amazing work

**Pull request merged**
