### PR TITLE
[MIG] delivery_carrier_preference: Migration to 14.0

### PR DESCRIPTION
**Pull request by dzungtran89**
Dependencies:
- stock_available_to_promise_release: https://github.com/OCA/wms/pull/184

### CODE REVIEW

**Review by sebalix — COMMENTED** [review]
LG, but the migration of the dependency https://github.com/OCA/wms/pull/184 has to be fixed

**Comment by hailangvn** [comment]
After #184 is merged, I will update this PR.

**Comment by hailangvn** [comment]
Good day @sebalix, @simahawk. This PR is updated and has green travis+runbot.

**Review by simahawk — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Comment by sebalix** [comment]
@hailangvn can you rebase please to resolve the conflict?

**Comment by hailangvn** [comment]
Good day @sebalix. The PR has been rebased and have green travis.

**Pull request merged**
