### PR TITLE
[15.0][MIG] stock_storage_type

### PR DESCRIPTION
**Pull request by flachica**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@flachica This one should stay on hold as Odoo model has changed (introduction of stock.package.type). We are having a discussion about it

**Comment by flachica** [comment]
Thanks @rousseldenis. In my company we are testing the system as it is. We haven't designed anything definitive yet and we can work on the adaptations that come out of that discussion. By the way, could I participate? In which forum are you commenting on these matters?

Cheers

**Comment by rousseldenis** [comment]
> Thanks @rousseldenis. In my company we are testing the system as it is. We haven't designed anything definitive yet and we can work on the adaptations that come out of that discussion. By the way, could I participate? In which forum are you commenting on these matters?
> 
> Cheers

For the moment, we discuss internally. But if you come on OCA days, we can meet

**Comment by flachica** [comment]
Sorry, this time I can't go to the OCA Days. Although if you deem it appropriate we could arrange a call

**Pull request closed without merging**
