### PR TITLE
[WIP][14.0][MIG] shopfloor

### PR DESCRIPTION
**Pull request by bguillot**
I continue the work done by @hparfr in https://github.com/OCA/wms/pull/90

I restarted from the branch 14.0.

### CODE REVIEW

**Comment by sebastienbeau** [comment]
I have done a rebase, as I have merge forward port from V13 into V14

**Comment by sebastienbeau** [comment]
Now we need to migrate dependency to make it green

**Comment by sebastienbeau** [comment]
@bguillot @hparfr module should be put as installable

**Comment by sebastienbeau** [comment]
base rest have now an official version for the V14 https://github.com/OCA/rest-framework/tree/14.0

**Comment by sebalix** [comment]
I'm closing this one as https://github.com/OCA/wms/pull/247 has been merged.

**Pull request closed without merging**
