### PR TITLE
[14.0][IMP] shopfloor: scenario location content transfer

### PR DESCRIPTION
**Pull request by mt-software-de**
make _find_location_move_lines from scan location hookable

### CODE REVIEW

**Review by jbaudoux — APPROVED** [review]

**Comment by simahawk** [comment]
@mt-software-de sorry for the nitpicking remark: as you see the commit msg is too long. Can you rewrite the commit msg?

```
[IMP] shopfloor: location content transfer add hook

Make _find_location_move_lines from scan location hookable.
```

**Comment by mt-software-de** [comment]
> @mt-software-de sorry for the nitpicking remark: as you see the commit msg is too long. Can you rewrite the commit msg?
> 
> ```
> [IMP] shopfloor: location content transfer add hook
> 
> Make _find_location_move_lines from scan location hookable.
> ```

no problem

**Comment by mt-software-de** [comment]
@simahawk could you approve this PR.?

**Pull request merged**
