### PR TITLE
[FIX] - stock_dynamic_routing: fix method params

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Comment by sbejaoui** [comment]
cc/ @lmignon

**Review by lmignon — APPROVED** [review]
Thank you @sbejaoui Indeed, this override doesn't preserve the original method signature.

**Comment by lmignon** [comment]
ping @OCA/logistics-maintainers

**Review by rousseldenis — APPROVED** [review]
Trivial

**Pull request merged**
