### PR TITLE
[16.0][ADD] stock_available_to_promise_release_exclude_location

### PR DESCRIPTION
**Pull request by jbaudoux**
Exclude locations from available stock.

This module allows to make the glue between stock_available_to_promise_release and stock_available_exclude_location

Depends on:
* https://github.com/OCA/stock-logistics-availability/pull/6

### CODE REVIEW

**Comment by jbaudoux** [comment]
@rousseldenis Ported to OCA

**Comment by jbaudoux** [comment]
rebased & removed do not merge commit as dependency is merged

**Comment by jbaudoux** [comment]
@sebalix @mmequignon Need review on this one (relates to BSCOS-4465 & BSALLO-559)

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by lmignon — APPROVED** [review]

**Pull request merged**
