### PR TITLE
[16.0][MIG] - shopfloor_workstation

### PR DESCRIPTION
**Pull request by sbejaoui**
needs:

- #679 
- #642 
- https://github.com/OCA/stock-logistics-workflow/pull/1330
- https://github.com/OCA/product-attribute/pull/1215

### CODE REVIEW

**Comment by lmignon** [comment]
@rousseldenis Can you reopen this one?

**Review by lmignon — APPROVED** [review]
Works in production for months

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
