### PR TITLE
[16.0][MIG] - shopfloor_rest_log

### PR DESCRIPTION
**Pull request by sbejaoui**
needs: 

- #642
- https://github.com/OCA/rest-framework/pull/354

### CODE REVIEW

**Comment by lmignon** [comment]
@sbejaoui can you reopen this PR PLZ?

**Comment by sbejaoui** [comment]
> @sbejaoui can you reopen this PR PLZ?

I don't have access to open, I believe only maintainers can

**Comment by lmignon** [comment]
@rousseldenis Can you reopen this one?

**Review by lmignon — APPROVED** [review]
Works like a charm in production for months

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
