### PR TITLE
[17.0][MIG] stock_warehouse_flow: Migration to 17.0 

### PR DESCRIPTION
**Pull request by peluko00**
Depends on:

- [delivery_procurement_group_carrier ] https://github.com/OCA/stock-logistics-workflow/pull/1570

### CODE REVIEW

**Comment by peluko00** [comment]
Module migrated to version 17.0

cc https://github.com/APSL 154330
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

 - [Issue] https://github.com/OCA/wms/issues/777

**Review by mpascuall — APPROVED** [review]
Works good, checked in runboat

**Review by lbarry-apsl — APPROVED** [review]
Tested on Runboat

**Review by sebalix — APPROVED** [review]

**Comment by sebalix** [comment]
Hello @peluko00, thanks for this contribution!
The dependency `delivery_procurement_group_carrier` has been merged, you can remove your TMP commit so this PR could be merged as well.

**Comment by peluko00** [comment]
> Hello @peluko00, thanks for this contribution! The dependency `delivery_procurement_group_carrier` has been merged, you can remove your TMP commit so this PR could be merged as well.

Done, ready for merge

**Review by sebalix — APPROVED** [review]

**Pull request merged**
