### PR TITLE
[16.0][IMP] stock_release_channel: add smart buttons on channel form view

### PR DESCRIPTION
**Pull request by victorvermot**
Result:

### CODE REVIEW

**Review by jbaudoux — APPROVED** [review]

**Comment by jbaudoux** [comment]
ping @lmignon @rousseldenis 

maybe we need to put singular instead of plural ?

**Comment by rousseldenis** [comment]
> ping @lmignon @rousseldenis
> 
> maybe we need to put singular instead of plural ?

Where ? If in buttons, no.

**Comment by jbaudoux** [comment]
The forced context `{"search_default_release_ready": 1}` in `action_picking_all` is not very convenient as you only see by default the release ready deliveries.
I would drop it.

**Comment by victorvermot** [comment]
I removed the context @jbaudoux but it makes one test fail and I am not sure how to fix it

**Comment by jbaudoux** [comment]
@victorvermot You need to adapt the test to remove what you removed from the context. See stock_release_channel.tests.test_channel_action: FAIL: TestChannelAction.test_action_all

**Comment by jbaudoux** [comment]
ping @victorvermot

**Comment by jbaudoux** [comment]
@victorvermot Thanks. Can you squash commits ?

**Comment by jbaudoux** [comment]
@victorvermot Can you squash commits ?

**Comment by victorvermot** [comment]
@jbaudoux Done

**Review by mt-software-de — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Pull request merged**
