### PR TITLE
[14.0][IMP] shopfloor_reception: Change select_move screen use manual-select

### PR DESCRIPTION
**Pull request by mt-software-de**
This will change the select_move screen of the reception scenario to use the manual-select component

### CODE REVIEW

**Comment by mt-software-de** [comment]
cc @jbaudoux @simahawk

**Review by jbaudoux — APPROVED** [review]

**Comment by mt-software-de** [comment]
I have removed the dependency to https://github.com/OCA/wms/pull/683

**Review by simahawk — APPROVED** [review]
LG

**Pull request merged**
