### PR TITLE
[14.0] shopfloor_base: add app menu icon

### PR DESCRIPTION
**Pull request by petrus-v**

### CODE REVIEW

**Comment by simahawk** [comment]
@petrus-v sounds good for starting! Could you please add the SVG too?

**Comment by petrus-v** [comment]
Oooopss I've used an online service to properly automatically create button with shadow giving png file as input which return png file... So I haven't svg version at the moment.

**Comment by simahawk** [comment]
could you do it when you have time? No rush of course :)

**Comment by petrus-v** [comment]
Yes, i'll give try !

Le ven. 26 nov. 2021 à 11:14, Simone Orsi ***@***.***> a
écrit :

**Review by hparfr — APPROVED** [review]
LGTM

**Review by sebalix — APPROVED** [review]
Nice icon, @petrus-v have you some news about the SVG?
@simahawk is it OK to merge it without SVG?

**Comment by simahawk** [comment]
icon included in #373 
@petrus-v when you can add SVG open another PR, tnx :pray:

**Pull request closed without merging**
