### PR TITLE
[16.0][FIX] stock_available_to_promise_release: add tagged to test

### PR DESCRIPTION
**Pull request by RodrigoBM**
add tagged post_install and "-at_install to run the module test the last one

### CODE REVIEW

**Comment by RodrigoBM** [comment]
This pr fixes bugs in the 16.0 branch of this repository.

Add any examples:
- https://github.com/OCA/wms/actions/runs/5749151445/job/15583421840?pr=704#step:8:40
- https://github.com/OCA/wms/actions/runs/5749296280/job/15583863839?pr=703#step:8:41
- https://github.com/OCA/wms/actions/runs/5713793688/job/15479845262?pr=697#step:8:41

cc: @rousseldenis @sbejaoui @jbaudoux

**Comment by RodrigoBM** [comment]
ping @OCA/logistics-maintainers

**Review by xAdrianCif — APPROVED** [review]
Changes needed!
Correct technical review, thank you!

**Review by jsanchezdeavila — APPROVED** [review]
LGTM

**Review by sebalix — APPROVED** [review]

**Pull request merged**
