### PR TITLE
[14.0][FIX] sf_single_product_transfer: fix backorder responsible

### PR DESCRIPTION
**Pull request by jbaudoux**
Remove user from backorder

cc @mmequignon

### CODE REVIEW

**Comment by mmequignon** [comment]
Why not setting "shopfloor_user_id" to False when copying the move line, in _split_partial_quantity ?
https://github.com/OCA/wms/blob/14.0/shopfloor/models/stock_move_line.py#L48

Also, when looking for move lines, why are we looking for move lines having their picking unassigned?
https://github.com/OCA/wms/blob/14.0/shopfloor_single_product_transfer/services/single_product_transfer.py#L230-L235
Why aren't we looking for move lines with  `shopfloor_user_id in (False, self.env.uid)` ?

**Comment by jbaudoux** [comment]
Rebased

**Comment by jbaudoux** [comment]
Can you review this one @Tdu @mt-software-de ?

**Review by mt-software-de — APPROVED** [review]
LGTM

**Pull request merged**
