### PR TITLE
[16.0] [ADD] stock_release_channel_shipment_lead_time

### PR DESCRIPTION
**Pull request by anothingguy**
depends on:
- https://github.com/OCA/wms/pull/550
- https://github.com/OCA/stock-logistics-transport/pull/88

### CODE REVIEW

**Review by cyrilmanuel — APPROVED** [review]
not an expert but LGTM

**Review by jbaudoux — APPROVED** [review]
LG

**Comment by simahawk** [comment]
Pending PRs have been merged, rebased!

**Review by simahawk — APPROVED** [review]

**Pull request merged**
