### PR TITLE
[16.0][PORT] stock_available_to_promise_release: Multi warehouse capability

### PR DESCRIPTION
**Pull request by sebalix**
Forward-port of https://github.com/OCA/wms/pull/818

Build fixed there:
- https://github.com/OCA/wms/pull/828

### CODE REVIEW

**Comment by sebalix** [comment]
Tests are failing because of the presence of `stock_release_channel_auto_release`, checking...

**Comment by sebalix** [comment]
Last test failing is in `stock_release_channel_batch_mode_commercial_partner`, digging...

**Review by santostelmo — APPROVED** [review]
LG

**Review by jbaudoux — APPROVED** [review]

**Comment by jbaudoux** [comment]
rebased

**Comment by jbaudoux** [comment]
@sbidoul pypi not updated on this one also

**Comment by sbidoul** [comment]
This was a transient issue on PyPI. The package will be published by the nightly bot jobs, please check again tomorrow.

**Pull request merged**
