### PR TITLE
[MIG] shopfloor_delivery_shipment: Migration to 14.0 

### PR DESCRIPTION
**Pull request by TDu**

### CODE REVIEW

**Comment by TDu** [comment]
I opened a fix on `stock-logistics-transport` for the failing tests.
https://github.com/OCA/stock-logistics-transport/pull/66

**Review by sebalix — APPROVED** [review]

**Review by mmequignon — APPROVED** [review]

**Comment by simahawk** [comment]
requires https://github.com/OCA/wms/pull/311

**Pull request merged**
