### PR TITLE
[16.0] [MIG] stock_dynamic_routing

### PR DESCRIPTION
**Pull request by lmignon**
* [x] depends on https://github.com/OCA/stock-logistics-warehouse/pull/1539
cc @rousseldenis @jbaudoux

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
LGTM

**Review by jbaudoux — APPROVED** [review]
LGTM

**Comment by lmignon** [comment]
@jbaudoux This one is ready to be merged....

**Comment by lmignon** [comment]
Thank you @simahawk

**Pull request merged**
