### PR TITLE
[14.0][PORT] 113 from 13.0

### PR DESCRIPTION
**Pull request by hparfr**
Port #113 from 13.0 to 14.0.

### CODE REVIEW

**Comment by hparfr** [comment]
@sebalix can you please review this one ?

**Review by sebalix — APPROVED** [review]
LG, thanks!

**Comment by simahawk** [comment]
You'll want to include this before merge maybe? 

https://github.com/OCA/wms/pull/148

**Comment by hparfr** [comment]
@simahawk I do each forward port separately.

**Pull request merged**
