### PR TITLE
[14.0] shopfloor_reception: fix test_done_action

### PR DESCRIPTION
**Pull request by JuMiSanAr**
Fix failing test.

### CODE REVIEW

**Review by mmequignon — APPROVED** [review]

**Comment by JuMiSanAr** [comment]
ping @TDu

**Review by TDu — APPROVED** [review]
LG, and faster.
So that lambda function returning a tuple was not working ?

**Comment by JuMiSanAr** [comment]
> LG, and faster. So that lambda function returning a tuple was not working ?

It wasn't, the result was not stored in a new variable...

**Review by sebalix — APPROVED** [review]

**Pull request merged**
