### PR TITLE
[13.0] stock_reception_screen: open from move line

### PR DESCRIPTION
**Pull request by TDu**
Add a reception button on the stock.move.line tree view to open the
reception screen.

### CODE REVIEW

**Review by guewen — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Comment by guewen** [comment]
I rebased this one, we should retry the merge if the build passes.

**Comment by guewen** [comment]
/ocabot merge minor

the issue we had on master is now fixed, if this tentative does not pass, a rebase will be needed

**Pull request merged**
