### PR TITLE
[13.0] Search ordered available to promise

### PR DESCRIPTION
**Pull request by santostelmo**
We want to give the possibility to search stock moves by `Ordered Available to Promise`

Also in Stock Moves To Release tree view, we just want to show moves with quantities available to release.

### CODE REVIEW

**Review by jgrandguillaume — APPROVED** [review]
Works well

**Comment by sebalix** [comment]
@jgrandguillaume the build issue came from an Ubuntu APT repository not available during the build, should be OK now I suppose

**Pull request merged**
