### PR TITLE
[14.0][IMP] stock_release_channel: refactor compute count

### PR DESCRIPTION
**Pull request by mt-software-de**
This PR makes it easier to extend the stock_release_channel module
it allows to easily extend the fields which should be computed

### CODE REVIEW

**Comment by mt-software-de** [comment]
cc @jbaudoux

**Comment by jbaudoux** [comment]
cc @sebalix @simahawk @lmignon

**Comment by mt-software-de** [comment]
ping @sebalix @simahawk @lmignon

**Review by simahawk — APPROVED** [review]
LG

**Review by lmignon — APPROVED** [review]

**Pull request merged**
