### PR TITLE
[IMP] shopfloor_reception_mobile: Make display values hookable

### PR DESCRIPTION
**Pull request by mt-software-de**

### CODE REVIEW

**Review by JuMiSanAr — APPROVED** [review]

**Comment by mt-software-de** [comment]
@simahawk this would bei needed for the reception purchase PR

**Review by TDu — APPROVED** [review]

**Comment by mt-software-de** [comment]
@jbaudoux could you please merge this PR?

**Comment by mt-software-de** [comment]
@jbaudoux this would be ready to merge.

**Pull request merged**
