### PR TITLE
[14.0][FIX] shopfloor: fix zone picking package as substitue on lines

### PR DESCRIPTION
**Pull request by TDu**
Use the content of the package (products) and not the product in the packaging description to search for possible move lines.

ref.: rau-122

### CODE REVIEW

**Review by simahawk — APPROVED** [review]
LG

**Review by jbaudoux — APPROVED** [review]

**Review by jbaudoux — CHANGES_REQUESTED** [review]
We need to collect all valid move lines, you cannot stop at the first product.

This is important as after this test, either you show a list of lines to choose from or you open the single valid one. So we need to know if there are many or one

**Comment by TDu** [comment]
> We need to collect all valid move lines, you cannot stop at the first product.
> 
> This is important as after this test, either you show a list of lines to choose from or you open the single valid one. So we need to know if there are many or one

done

**Review by jbaudoux — APPROVED** [review]
Thanks. LG now

**Review by sebalix — APPROVED** [review]

**Pull request merged**
