### PR TITLE
[14.0] Shopfloor: Control the display of the virtual keyboard (Gboard) + SECURITY FIX

### PR DESCRIPTION
**Pull request by jbaudoux**
Fwd port of https://github.com/OCA/wms/pull/345

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Comment by simahawk** [comment]
@jbaudoux could you split 1 commit in another PR? It would help integration w/ #316

**Comment by simahawk** [comment]
Nevermind, I'll take care of this and cherry-pick changes

**Comment by jbaudoux** [comment]
rebased

**Comment by simahawk** [comment]
@jbaudoux can you rebase again pls?

Also, please rewrite commits as

```

shopfloor_mobile_base: control virtual keyboard display

shopfloor_mobile_base: fix login form security

```

and split int is commit the change for using the searchbar in the api key form.

**Comment by jbaudoux** [comment]
The commit for the change of the apikey input field has been extracted in a separate PR https://github.com/OCA/wms/pull/412

**Comment by simahawk** [comment]
@jbaudoux cool, tnx, can you rebase?

**Comment by jbaudoux** [comment]
@simahawk rebased

**Review by TDu — APPROVED** [review]

**Comment by jbaudoux** [comment]
rebased

**Comment by jbaudoux** [comment]
@sebalix @simahawk Can you merge this one? I have rebased it

**Pull request merged**
