### PR TITLE
[14.0][IMP] shopfloor: refactor cancel_work to offer more hooks for override

### PR DESCRIPTION
**Pull request by mt-software-de**

### CODE REVIEW

**Comment by mt-software-de** [comment]
@jbaudoux could please review this change?

**Review by jbaudoux — APPROVED** [review]

**Review by jbaudoux — APPROVED** [review]

**Comment by jbaudoux** [comment]
@sebalix

**Comment by mt-software-de** [comment]
@simahawk could you mabye review this as well?

**Review by simahawk — APPROVED** [review]
LG

**Pull request merged**
