### PR TITLE
[FIX] stock_reception_screen: forbid view locations

### PR DESCRIPTION
**Pull request by sebalix**
Ref. 1815

### CODE REVIEW

**Review by TDu — APPROVED** [review]

**Comment by simahawk** [comment]
@sebalix are you able to reproduce the error in the build?

**Comment by simahawk** [comment]
> @sebalix are you able to reproduce the error in the build?

BTW is the same error I have here https://github.com/OCA/wms/pull/99 but I was not able to replicate it :cry:

**Comment by sebalix** [comment]
@simahawk rebased

**Pull request merged**
