### PR TITLE
[16.0][FIX] stock_available_to_promise_release : unrelease when no pick left

### PR DESCRIPTION
**Pull request by jbaudoux**
When the pick is partially processed but no backorder is kept, the backorder of the ship must be unreleasable

The pick backorder strategy is configured to never.

cc @TDu @sebalix @rousseldenis @lmignon

### CODE REVIEW

**Comment by lmignon** [comment]
> When the pick is partially processed but no backorder is kept, the backorder of the ship must be unreleasable
> 
> The pick backorder strategy is configured to never.
> 
> cc @TDu @sebalix @rousseldenis @lmignon

A simple question? Is the backorder of the pick linked to the backorder of the ship?

**Comment by jbaudoux** [comment]
> A simple question? Is the backorder of the pick linked to the backorder of the ship?

In this case, there is no pick backorder. But the backorder of the ship is linked to the done pick

**Comment by lmignon** [comment]
> > A simple question? Is the backorder of the pick linked to the backorder of the ship?
> 
> In this case, there is no pick backorder. But the backorder of the ship is linked to the done pick

Indeed, my bad the answer is into your PR description and the code...`self.picking.picking_type_id.create_backorder = "never"`

**Review by lmignon — APPROVED** [review]
Code review

**Review by santostelmo — APPROVED** [review]

**Pull request merged**
