### PR TITLE
[14.0] dotfiles update needs manual intervention

### PR DESCRIPTION
**Pull request by sbidoul**
Dear maintainers,

After updating the dotfiles, `pre-commit run -a` fails in a manner that cannot be resolved automatically.
Can you please have a look, fix and merge?

Thanks,

### CODE REVIEW

**Comment by simahawk** [comment]
@sbidoul thanks! I'll check in a while.

**Comment by sbidoul** [comment]
Probably due to modules missing installable=False on this branch.

**Comment by simahawk** [comment]
@bguillot as you are working on v14 already, could you check?

**Comment by simahawk** [comment]
@sbidoul fixed. Runbot is red only because there's nothing to test (no module installable).

**Comment by simahawk** [comment]
@hparfr @bguillot you should rebase your work now :wink:

**Pull request merged**
