### PR TITLE
[14.0][FIX] delivery_carrier_preference: Fix tests

### PR DESCRIPTION
**Pull request by kv1612**

### CODE REVIEW

**Comment by sebalix** [comment]
As there was already a migration done this module here: https://github.com/OCA/wms/pull/185 and that your PR fix the tests (thank you!) I suppose you could rename your commit accordingly to not have two v14 migration commits.
For me it is a fix of tests, the current business code didn't change so that's fine.

**Review by sebalix — COMMENTED** [review]
As there was already a migration done this module here: https://github.com/OCA/wms/pull/185 and that your PR fix the tests (thank you!) I suppose you could rename your commit accordingly to not have two v14 migration commits.
For me it is a fix of tests, the current business code didn't change so that's fine.

**Comment by kv1612** [comment]
Hello @sebalix, I have just updated the commit message and the PR's title. Thank you for the suggestion

**Review by sebalix — APPROVED** [review]

**Pull request merged**
