### PR TITLE
[14.0][IMP] shopfloor: Zone picking - set destination location check into own method

### PR DESCRIPTION
**Pull request by mt-software-de**
Move the checks for set location into own method.
This allows us to hook/extend the checks from different addons.

### CODE REVIEW

**Comment by mt-software-de** [comment]
cc @jbaudoux @TDu

**Review by TDu — APPROVED** [review]

**Comment by jbaudoux** [comment]
cc @mmequignon

**Comment by mt-software-de** [comment]
ping @jbaudoux @mmequignon

**Review by jbaudoux — APPROVED** [review]

**Pull request merged**
