### PR TITLE
[16.0][MIG] - shopfloor_mobile_base

### PR DESCRIPTION
**Pull request by sbejaoui**
needs:

- #642

### CODE REVIEW

**Comment by jbaudoux** [comment]
@sbejaoui Can you drop from your migration commit the reformat of the external libs in shopfloor_mobile_base/static/wms/src/ ?
Can you put the exclude of this you added in precommit in a separate commit before the migration commit?

**Comment by lmignon** [comment]
@rousseldenis @jbaudoux Works in production for months. Can we merge-it?

**Review by lmignon — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
