### PR TITLE
shopfloor: Improve package and product details

### PR DESCRIPTION
**Pull request by TDu**
Adds on the package details:

* the actual stock location of the package
* the barcode of the product

And also add the barcode on the product details.

### CODE REVIEW

**Comment by guewen** [comment]
This test fails: `shopfloor.tests.test_actions_data_detail: FAIL: ActionsDataDetailCase.test_data_package`.

Unrelated, but ActionsDataDetailCase miss the `Test` prefix.

**Comment by TDu** [comment]
I fixed the test and rename test class that needed to be.

**Review by simahawk — APPROVED** [review]

**Review by guewen — APPROVED** [review]

**Comment by simahawk** [comment]
I've canceled the build. I'll merge all approved PRs and bump only after the last. They can all be part of the same release.

**Pull request merged**
