### PR TITLE
[16.0][IMP] stock_release_channel: track `release_channel_id` on `stock.picking`

### PR DESCRIPTION
**Pull request by IT-Ideas**
This commit adds the changes tracking on `release_channel_id` of `stock_picking`

### CODE REVIEW

**Review by sbejaoui — APPROVED** [review]

**Comment by RodrigoBM** [comment]
@IT-Ideas change name to [16.0][IMP] stock_release_channel: track release_channel_id on stock.picking

**Comment by IT-Ideas** [comment]
> @IT-Ideas change name to [16.0][IMP] stock_release_channel: track release_channel_id on stock.picking

Hello @RodrigoBM, are you talking about the PR name or the commit title? In the commit history I don't find any with this pattern. Am I missing something?

**Comment by RodrigoBM** [comment]
> > @IT-Ideas change name to [16.0][IMP] stock_release_channel: track release_channel_id on stock.picking
> 
> Hello @RodrigoBM, are you talking about the PR name or the commit title? In the commit history I don't find any with this pattern. Am I missing something?

PR name, I haven't found this in the documentation, but you can see these example PR names

Selección_670

**Comment by jbaudoux** [comment]
@IT-Ideas Can you rebase? The fix for failing test has been merged.

**Comment by IT-Ideas** [comment]
> @IT-Ideas Can you rebase? The fix for failing test has been merged.

Yep but it seems that 16.0 is still red. Should I still do it?

**Comment by rousseldenis** [comment]
> > > @IT-Ideas change name to [16.0][IMP] stock_release_channel: track release_channel_id on stock.picking
> > 
> > 
> > Hello @RodrigoBM, are you talking about the PR name or the commit title? In the commit history I don't find any with this pattern. Am I missing something?
> 
> PR name, I haven't found this in the documentation, but you can see these example PR names
> 
> Selección_670

@RodrigoBM When doing an imporvement, it's better to not include the version number in commit message as the fix is often transversal to several versions. This allows to be forwardported or backported flawlessly.

**Comment by rousseldenis** [comment]
@IT-Ideas Could you rebase ?

**Comment by IT-Ideas** [comment]
Here you go @rousseldenis 🙂

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
