### PR TITLE
[16.0][FW][IMP] stock_available_to_promise_release: Own field for release policy

### PR DESCRIPTION
**Pull request by mt-software-de**
FW Port https://github.com/OCA/wms/pull/793

### CODE REVIEW

**Comment by mt-software-de** [comment]
cc @jbaudoux @sebalix

**Comment by sebalix** [comment]
Glad to see the same test failing there, I couldn't find the reason why it was failing with the port here: https://github.com/OCA/wms/pull/823 :)
I made a fix in the same PR, I'll extract it to merge it ASAP in 16.0.

**Comment by sebalix** [comment]
https://github.com/OCA/wms/pull/828

**Comment by jbaudoux** [comment]
@mt-software-de rebase and drop fix on stock_release_channel_batch_mode_commercial_partner

**Comment by mt-software-de** [comment]
> @mt-software-de rebase and drop fix on stock_release_channel_batch_mode_commercial_partner

done

**Review by sebalix — APPROVED** [review]

**Comment by mt-software-de** [comment]
ping @jbaudoux

**Review by jbaudoux — APPROVED** [review]
@mt-software-de Can you rebase? i'll merge it

**Comment by mt-software-de** [comment]
> @mt-software-de Can you rebase? i'll merge it

done

**Pull request merged**
