### PR TITLE
[IMP] stock_available_to_promise_release: Improve migration/init script to initialize 'release_policy' field with default values

### PR DESCRIPTION
**Pull request by rousseldenis**
The upgrade script should initialize the value with the sql default instead updating every existing record (maybe billions).

### CODE REVIEW

**Comment by rousseldenis** [comment]
@jbaudoux @mt-software-de

**Comment by rousseldenis** [comment]
This is the magic:

image

**Comment by mt-software-de** [comment]
Many thanks yes this was missing. 
Why did not set the release_policy as it is done here?
https://github.com/OCA/wms/blob/111d87780457fa740dc0cc5609c47ab26be5916d/stock_available_to_promise_release/migrations/16.0.3.1.0/post-migrate.py#L5

**Comment by rousseldenis** [comment]
> Many thanks yes this was missing. Why did not set the release_policy as it is done here?
> 
> https://github.com/OCA/wms/blob/111d87780457fa740dc0cc5609c47ab26be5916d/stock_available_to_promise_release/migrations/16.0.3.1.0/post-migrate.py#L5

Here, I initialize the field with the default value, so, it should be done in pre script.

I've put it also in pre-init as the module can be installed on huge database too

**Comment by mt-software-de** [comment]
> > Many thanks yes this was missing. Why did not set the release_policy as it is done here?
> > https://github.com/OCA/wms/blob/111d87780457fa740dc0cc5609c47ab26be5916d/stock_available_to_promise_release/migrations/16.0.3.1.0/post-migrate.py#L5
> 
> Here, I initialize the field with the default value, so, it should be done in pre script.
> 
> I've put it also in pre-init as the module can be installed on huge database too


> > Many thanks yes this was missing. Why did not set the release_policy as it is done here?
> > https://github.com/OCA/wms/blob/111d87780457fa740dc0cc5609c47ab26be5916d/stock_available_to_promise_release/migrations/16.0.3.1.0/post-migrate.py#L5
> 
> Here, I initialize the field with the default value, so, it should be done in pre script.
> 
> I've put it also in pre-init as the module can be installed on huge database too

Yes i have seen this, but why we don't remove the post_migration
and moving the post_migration part into the new init method?

**Review by jbaudoux — APPROVED** [review]

**Comment by jbaudoux** [comment]
replaced by https://github.com/OCA/wms/pull/931

**Pull request closed without merging**
