### PR TITLE
[16.0][FIX] stock_available_to_promise_release: Fix unrelease on backorder …

### PR DESCRIPTION
**Pull request by lmignon**
…moves

When we check if we can release a move, we must only check the remeaining qties on origin moves that are not canceled or done and not part of a printed picking.

Before this change, we checked the 'printed' flag on origin moves's pickings. This check wil not work for backorder moves since in suck a case, the origin moves will be at same time in a 'printed' picking for the qty already processed and delivered and into a picking to do for the remaining qty.

### CODE REVIEW

**Comment by lmignon** [comment]
ping @jbaudoux @rousseldenis @TDu

**Comment by jbaudoux** [comment]
If you partially process the picking, somehow you started working on the order and you should not be able to unrelease.
With your change, it can leads to issues when you do grouped picking (picking move serving multiple deliveries). Example:
move1 on locX for prodA for SO1 qty 3 is done
move2 on locY for prodA for SO1 & SO2 & SO3 with qty 6 (2 for SO1, 2 for SO2, 2 for SO3).
You should not be able to unrelease SO1 while unprocessed move2 qty 6 > SO1 qty 5

**Review by jbaudoux — CHANGES_REQUESTED** [review]
Needs clarification

**Comment by rousseldenis** [comment]
@lmignon

**Pull request closed without merging**
