### PR TITLE
[14.0] shopfloor_mobile_base: add min.js files in lib

### PR DESCRIPTION
**Pull request by JuMiSanAr**
The external libraries in shopfloor_mobile_base now use min.js files, reducing the size of the resources used in the browser.

### CODE REVIEW

**Comment by simahawk** [comment]
@JuMiSanAr have you run UI tests after this change?

**Review by simahawk — APPROVED** [review]
LG

**Comment by simahawk** [comment]
> @JuMiSanAr have you run UI tests after this change?

answer: yes

**Comment by JuMiSanAr** [comment]
> @JuMiSanAr have you run UI tests after this change?

**Pull request merged**
